######################################################################
# Automatically generated by qmake (3.0) ?? ??? 11 19:22:46 2016
######################################################################

TEMPLATE = app
TARGET = Isomorphizm
INCLUDEPATH += .

# Input
HEADERS += graph.h
SOURCES += graph.cpp main.cpp
